#!/usr/bin/env python3
"""Packs the Amiga Larn tiles (port/amiga/*.png, 8x16, from larn.org /
github.com/primeau/Larn, MIT) into port/tiles.rgba and writes port/tilemap.h.

Tile names follow primeau's Larn: mN = monster N, oN = object N, wN = wall
with neighbour bits (2 up, 4 right, 8 down, 16 left). Larn 12.x numbering
matches RL_M except where OBJ_REMAP says so. Run from the repo root."""
import struct
from pathlib import Path
from PIL import Image

SRC = Path("port/amiga")
PER_ROW = 32
MAXMONST_IDS = 65          # 0..64 (DEMONPRINCE)
MAXOBJECT = 97
# RL_M object id -> primeau image; None = no tile (drawn as text)
OBJ_REMAP = {80: 82, 82: 80, 84: None, 93: None, 94: None, 95: None, 96: "wall", 97: None}

names = []


def add(name):
    if name not in names:
        names.append(name)
    return names.index(name)


mon = [add(f"m{i}") for i in range(MAXMONST_IDS)]
obj = []
for i in range(MAXOBJECT + 1):
    r = OBJ_REMAP.get(i, i)
    obj.append(-2 if r == "wall" else -1 if r is None else add(f"o{r}"))
wall = [add(f"w{m}") for m in range(0, 32, 2)]
player = add("player")

rows = (len(names) + PER_ROW - 1) // PER_ROW
sheet = Image.new("RGBA", (PER_ROW * 8, rows * 16))
for i, n in enumerate(names):
    t = Image.open(SRC / f"{n}.png").convert("RGBA")
    if t.size != (8, 16):  # o90 (Vorpal Blade) is 13x20 upstream
        t = t.resize((8, 16), Image.NEAREST)
    sheet.paste(t, ((i % PER_ROW) * 8, (i // PER_ROW) * 16))
with open("port/tiles.rgba", "wb") as f:
    f.write(struct.pack("<II", *sheet.size))
    f.write(sheet.tobytes())
sheet.save("port/tiles.png")


def arr(a):
    return ",".join(map(str, a))


Path("port/tilemap.h").write_text(f"""/* Generated by port/mktiles.py from the Amiga Larn tiles. Do not edit. */
static const short mon_tile[{len(mon)}] = {{{arr(mon)}}};
/* -1 = text, -2 = wall (wall_tile by neighbours) */
static const short obj_tile[{len(obj)}] = {{{arr(obj)}}};
static const short wall_tile[16] = {{{arr(wall)}}};
#define PLAYER_TILE {player}
""")
print(len(names), "tiles")
